all:
	fpc -Sd ./GeneralizedSuffixTreeTest.lpr -Fu../ -Fu../../../my-units/General-Purpose-Units/

memleak:
	fpc -gh -g -gl -Sd ./GeneralizedSuffixTreeTest.lpr -Fu../ -Fu../../../my-units/General-Purpose-Units/ -FU/tmp -Fu../../../my-units/PB2PAS
